### ISSUE TITLE
Code is not compatible with most recent yew 'master' code base

### ISSUE THREAD

**Issue by goodidea-kp** [thedodd/ybc#27]
I want to use a new version of workers from 'yew'master' - which is working for me.
However, I can't compile it with the current version of ybc. Please spend some time migrating on the recent 'yew' version.

Thank you!

**Comment by mneilly** [comment]
FWIW - you can try this branch:

https://github.com/mneilly/ybc/tree/yew-0-19-update

which is just https://github.com/thedodd/ybc/pull/25 rebased on the latest master. 

Also, I have an updated ybc-example repo that works with the above:

https://github.com/mneilly/ybc-example/tree/mneilly/update-to-ybc-yew19

I make no quality claims and haven't done any testing... these are just me trying to get things running so I can experiment with ybc.

**Comment by thedodd** [comment]
Updated 🎉
